[#36] feat: Inquiry UI & vulnerability-db app router 설계
hyeonji1125/sfacspace-06-project pull request #38
Opened 2024-08-15 02:33 UTC by HeoMinSeok

## Description
- 고객 문의 반응형 디자인 (다크 모드 적용) 완료했습니다. 
- 추후 디테일하게 수정하겠습니다.
- 취약점DB 라우터 설정 ( 로그인 모달 )

## Screenshots
<img width="1870" alt="image" src="https://github.com/user-attachments/assets/76ff9b23-4a49-4a2f-bd4a-53dd7c92072b">
<img width="1817" alt="image" src="https://github.com/user-attachments/assets/2ad6fa19-2eb0-43c3-8921-85b9e68c51d7">

## IssueNumer
#36

2024-08-15 13:16 UTC, aoooec requested changes

2024-08-15 13:16 UTC, aoooec commented on .storybook/main.ts
> +  staticDirs: ["../public"],
민석님 이부분 원래 작성되어있는걸로 변경해주셔야해요!
mac / win 둘 다 정상 동작하는 코드입니다. 아래 코드는 mac에서만 돌아가서 pr 올릴때마다 계속 변경되는거 수정하지 않으려면 위 코드대로 해야해욤

2024-08-15 13:16 UTC, aoooec commented on package.json
> +  "packageManager": "yarn@1.22.22+sha1.ac34549e6aa8e7ead463a7407e1c7390f61a6610"
`yarn`이 계속 님을 쫓아다니는데요

2024-08-15 13:16 UTC, aoooec commented on src/app/(home)/_components/Inquiry.tsx
> +}
저희 `interface` 말고 `type` 공통으로 쓰기로 해서 변경 부탁드려용!

2024-08-15 13:16 UTC, aoooec commented on src/app/(home)/_components/Inquiry.tsx
> +            </button>
여기도 하나님이 작업해주신 공통 버튼 컴포넌트로 대체해주시면 될것같아요!

2024-08-15 13:16 UTC, aoooec commented on src/app/(home)/_components/Inquiry.tsx
> +          <h2 className="text-3xl md:text-[60px] leading-tight md:leading-[1.5] text-primary-purple-500 text-left mb-4 md:mb-[30px]">서비스이용에 <span className="hidden md:inline"><br /></span>문제가 생겼나요?</
`font-bold`가 추가되어야 할 것 같아요!

2024-08-15 13:16 UTC, aoooec commented on src/components/common/Header.tsx
> +        </Link>
여기 컨플릭트 해결이 잘못된것같아요! 
기존이 하나님이 수정해주신 로고 전체 `svg` 버전이라서 (텍스트 자체 패딩 위치 관련 `mac`, `win` 불일치때문에 아예 이미지 파일로 이용하기로 함) 기존 코드를 `Link` 태그로만 감싸주시면 될 것 같아요. 
`svg` 태그 자체를 이미지처럼 사용하는 경우(`FlawDetectorLogo`) 별도의 `alt` 속성을 사용할 수 없어서 찾아보니 아래와 같은 해결책이 있네용 

>  a. Svg 가장 상위 태그에 title, desc 태그로 설명을 덧붙입니다. title에는 기본적인 설명을, desc에는 부연설명이 있을 경우 추가하면 됩니다. b. W3C에서는 이렇게만 해도 접근성에 문제가 없는 것으로 명시를 하고 있지만 아직 브라우저의 접근성 api에서 위의 방법대로만 처리할경우 스크린리더에게 정보를 제대로 전달해주지 못하는 문제가 있어 추가적으로 title에 aria-labelledby를, desc에 aria-describedby 속성을 추가합니다.
```typescript
<svg version="1" id="cat" viewBox="0 0 720 800" aria-labelledby="catTitle” aria-describedby=”catDesc" role="img">
  <title id="catTitle">친근한 고양이</title>
  <desc id="catDesc">회색고양이가 주인에게 안겨 있는 모습</desc>
  … 
</svg>
```
출처: https://nuli.navercorp.com/community/article/1132853

2024-08-15 13:16 UTC, aoooec commented on tailwind.config.ts
> +        "primary-gray": {
여기는 이름을 왜 변경하셨을까요!? 
일단 `primary gray`라는 명칭이 옳지 않은 것 같습니당 (`primary` 컬러가 아니기 때문에) 
그리고 다수의 다른 기본 컴포넌트에서 사용하고 있을 확률이 높은 컬러라 변경이 필요하다면 사전에 상의가 필요한 부분으로 보여요!

2024-08-15 13:16 UTC, aoooec commented on tailwind.config.ts
> +        },
그리고 순서를 바꾸신것도 이유가 있을까요?
일반적으로 100->0 순으로 진한 컬러 -> 연한 컬러로 사용하는데 반대로 변경해주셔서요!

2024-08-16 12:59 UTC, rl0425 commented on src/components/common/Header.tsx
> +            <span className="cursor-pointer hover:text-custom-text-hover">취약점 DB</span>
혹시 Link 태그 하단에 span 태그를 사용하신 이유가 있으실까요? 의미론적이나 접근성 측면에서 Link 태그 안의 텍스트 요소는 a 태그를 사용하는 걸로 알고 있습니다!
```
ex)
import Link from 'next/link'
import styled from 'styled-components'
 
// This creates a custom component that wraps an <a> tag
const RedLink = styled.a`
  color: red;
`
 
function NavLink({ href, name }) {
  return (
    <Link href={href} passHref legacyBehavior>
      <RedLink>{name}</RedLink>
    </Link>
  )
}
 
export default NavLink
``` 
[https://nextjs.org/docs/pages/api-reference/components/link](url)

2024-08-19 06:49 UTC, HeoMinSeok commented on src/components/common/Header.tsx
> +            <span className="cursor-pointer hover:text-custom-text-hover">취약점 DB</span>
아 저거는 아직 구현 전이라 잠시 넣어뒀습니다 글자만!!! 테스트해본다고 임의로 넣은거라 수정했습니다!

2024-08-19 07:01 UTC, HeoMinSeok commented on src/components/common/Header.tsx
> +            <span className="cursor-pointer hover:text-custom-text-hover">취약점 DB</span>
수정했습니다 ! 우선은 라우트 잘 넘어가는지 확인만하려고 넣어뒀던거라 디테일한 부분은 신경 못 썼었엇네요!

2024-08-19 14:15 UTC, aoooec approved these changes
아휴 고생하셨습니다!! 👍

2024-08-19 14:15 UTC, aoooec commented on src/app/(home)/_components/Inquiry.tsx
> +    <section className="flex flex-col lg:flex-row min-h-[800px] my-8 md:my-[103px] justify-between px-4 md:px-8 xl:px-20 2xl:px-0 gap-y-8 lg:gap-y-0 lg:gap-x-16">
`<div className="px-4 sm:px-8 md:px-[60px] lg:px-[120px] xl:px-[190px]">` 
아까 말씀드렸던건 이 `(home)/page.tsx`에서 `ContactForm(Inquiry)`를 감싸고 있는 `div`의 `css` 속성을 `section`이나 내부 `div`에 부여해도 될것같다는 의미였어욤! (`Inquiry.tsx`를 사용하는 두 곳에서 동일한 레이아웃을 사용하기 때문에)

2024-08-19 14:24 UTC, hyeonji1125 approved these changes

2024-08-19 17:56 UTC, merged